"""empty message

Revision ID: 20cf6aaa39d4
Revises: 94a34ff1f654
Create Date: 2023-09-18 17:43:42.610545

"""
from alembic import op
import sqlalchemy as sa
import os

environment = "production" if os.environ.get("FLASK_DEBUG") == 0 else "development"
SCHEMA = os.environ.get("FLASK_SCHEMA")


# revision identifiers, used by Alembic.
revision = "20cf6aaa39d4"
down_revision = "94a34ff1f654"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    if environment == "production":
        op.execute(f"ALTER TABLE messages SET SCHEMA {SCHEMA};")
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    op.drop_table("user")
    op.drop_table("message")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("content", sa.VARCHAR(length=2000), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(length=255), nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("users")
    op.drop_table("messages")
    # ### end Alembic commands ###
