"""empty message

Revision ID: 4471194c0873
Revises: c764d2db8e91
Create Date: 2023-09-19 21:22:02.577153

"""
from alembic import op
import sqlalchemy as sa
import os

environment = os.environ.get("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = "4471194c0873"
down_revision = "c764d2db8e91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "messages", schema=SCHEMA if environment == "production" else None
    ) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_messages_user_id_users"), "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "messages", schema=SCHEMA if environment == "production" else None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_messages_user_id_users"), type_="foreignkey"
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
