"""empty message

Revision ID: 7b661a6a2d78
Revises: 03be6f71bdd7
Create Date: 2023-09-21 18:37:13.885233

"""
from alembic import op
import sqlalchemy as sa
import os

environment = "production" if os.environ.get("FLASK_DEBUG") == 0 else "development"
SCHEMA = os.environ.get("FLASK_SCHEMA")


# revision identifiers, used by Alembic.
revision = "7b661a6a2d78"
down_revision = "03be6f71bdd7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "direct_messages", schema=SCHEMA if environment == "production" else None
    ) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_direct_messages_user_id_users"), "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "direct_messages", schema=SCHEMA if environment == "production" else None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_direct_messages_user_id_users"), type_="foreignkey"
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
