"""empty message

Revision ID: 94a34ff1f654
Revises: 
Create Date: 2023-09-18 17:39:13.667900

"""
from alembic import op
import sqlalchemy as sa
import os

environment = (
    "production" if os.environ.get("FLASK_DEBUG") == "False" else "environment"
)
SCHEMA = os.environ.get("FLASK_SCHEMA")


# revision identifiers, used by Alembic.
revision = "94a34ff1f654"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    if environment == "production":
        op.execute(f"ALTER TABLE message SET SCHEMA {SCHEMA};")

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE user SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("message")
    # ### end Alembic commands ###
